name: CI/CD para Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Iniciar sesión en Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Construir y subir imagen Docker
      run: |
        docker build -t jhonatan.azurecr.io/flask-backend:latest .
        docker push jhonatan.azurecr.io/flask-backend:latest

    - name: Desplegar en Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: flask-backend-app
        images: tu-registro-acr.azurecr.io/flask-backend:latest

